Update snapshot-window-azure-stream-analytics.md
MicrosoftDocs/azure-reference-other pull request #153
Opened 2021-06-17 01:18 UTC by ClemensSzyperski

Fixed a typos. (It is _indeed_ unusual to expect input events at exactly the same time.)

2021-06-17 01:18 UTC, PRMerger15 commented
@ClemensSzyperski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-06-17 03:50 UTC, Fleid commented
Hi @ClemensSzyperski, thanks for the feedback!

I think the original meaning was intended. It justifies the scenario that comes after (doing a snapshot window after another type of windowing).

Now I agree with you that the point is up for debate. I may just rewrite the blurb to avoid the argument completely. 
Something like:

_A common usage for snapshot windows is to aggregate events after they have been grouped on a single timestamp via a preceding window function, like TumblingWindow below._

What do you think?

2021-06-21 17:41 UTC, Fleid requested changes
Hi @ClemensSzyperski, thanks for the feedback!

I think the original meaning was intended. It justifies the scenario that comes after (doing a snapshot window after another type of windowing).

Now I agree with you that the point is up for debate. I may just rewrite the blurb to avoid the argument completely.
Something like:

A common usage for snapshot windows is to aggregate events after they have been grouped on a single timestamp via a preceding window function, like TumblingWindow below.

What do you think?

2021-07-05 18:59 UTC, Fleid commented
Moved forward with my suggestion on another PR.
#please-close

2021-07-08 16:58 UTC, Fleid commented
#please-close

2021-07-08 16:58 UTC, closed without merging